/**
 * Hermes Agent Security Config Generator
 * ---------------------------------------
 * Shared between:
 *   /api/generate-hermes-config  → zip bundle download
 *   /s/[token]                   → CLI setup URL (--from flag)
 */

export interface HermesConfig {
  projectName: string;
  repoUrl: string;
  tools: Array<{ name: string; sourceUrl?: string }>;
  memoryLayers: ('episodic' | 'semantic' | 'working')[];
  hasSubAgents: boolean;
  hasManifest: boolean;
  manifestPath: string;
  framework: string;
  ciProvider: 'github' | 'gitlab' | 'none';
}

export interface GeneratedFile {
  path: string;
  content: string;
}

// ── Generators ─────────────────────────────────────────────────────────────

export function generateAgentManifest(config: HermesConfig): string {
  const tools = config.tools.map(t => ({
    name: t.name,
    ...(t.sourceUrl
      ? { source: t.sourceUrl, integrity: '# run: npx ship-safe hash <source-url>' }
      : { local: true }),
    permissions: ['read'],
  }));

  return JSON.stringify(
    {
      $schema: 'https://shipsafecli.com/schemas/agent-manifest.v1.json',
      name: config.projectName || 'my-hermes-agent',
      version: '1.0.0',
      description: 'Hardened agent manifest — generated by Ship Safe',
      tools,
      security: {
        allowlist: config.tools.map(t => t.name),
        maxRecursionDepth: config.hasSubAgents ? 3 : 1,
        requireIntegrity: true,
        memoryValidation: config.memoryLayers.length > 0,
      },
    },
    null,
    2,
  );
}

export function generateHermesPolicy(config: HermesConfig): string {
  const allowlist = config.tools.map(t => `'${t.name}'`).join(', ');

  const memoryChecks =
    config.memoryLayers.length > 0
      ? `
    // Memory layer validation
    const MEMORY_PATTERNS = [/\\.hermes\\/memory/, /episodic\\/|semantic\\/|working\\//];
    for (const file of files) {
      if (!MEMORY_PATTERNS.some(p => p.test(file))) continue;
      let content;
      try { content = fs.readFileSync(file, 'utf-8'); } catch { continue; }
      const lines = content.split('\\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (/ship-safe-ignore/i.test(line)) continue;
        if (/JSON\\.parse\\s*\\((?!.*schema|.*validate)/i.test(line)) {
          findings.push(createFinding({
            rule: 'HERMES_MEMORY_UNSAFE_DESERIALIZE', severity: 'high',
            title: 'Memory deserialized without schema validation',
            description: 'JSON.parse on memory data without schema validation allows poisoned memory to inject arbitrary values.',
            file, line: i + 1, matched: line.trim().slice(0, 120), category: 'llm',
            remediation: 'Validate memory structure with zod or ajv before use.',
            confidence: 'medium',
          }));
        }
      }
    }`
      : '';

  return `/**
 * hermes-policy.js — Ship Safe Hermes Security Policy
 * Generated by: npx ship-safe init --hermes
 * Project: ${config.projectName || 'my-hermes-agent'}
 * Date: ${new Date().toISOString().split('T')[0]}
 *
 * Enforces: tool allowlist, function-call injection detection,
 * memory validation, sub-agent trust boundaries.
 *
 * Place in .ship-safe/agents/ — runs on every \`ship-safe audit\`.
 */

import fs from 'fs';

let BaseAgent, createFinding;
try {
  ({ BaseAgent, createFinding } = await import('ship-safe'));
} catch {
  ({ BaseAgent, createFinding } = await import('../agents/base-agent.js'));
}

const ALLOWED_TOOLS = [${allowlist}];

const DYNAMIC_TOOL_PATTERNS = [
  /toolName\\s*=\\s*(?:response|llmOutput|message|completion|result)[\\.\\[]/i,
  /dispatch\\(\\s*(?:response|llmOutput|completion)[\\.\\[]/i,
  /execute\\(\\s*(?:response|llmOutput|completion)[\\.\\[]/i,
  /invoke\\(\\s*(?:response|llmOutput|completion)[\\.\\[]/i,
];

export default class HermesPolicy extends BaseAgent {
  constructor() {
    super();
    this.name     = 'HermesPolicy';
    this.category = 'llm';
  }

  async analyze({ files = [] }) {
    const findings = [];
    for (const file of files.filter(f => /\\.(js|ts|jsx|tsx)$/.test(f))) {
      let content;
      try { content = fs.readFileSync(file, 'utf-8'); } catch { continue; }
      const lines = content.split('\\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (/ship-safe-ignore/i.test(line)) continue;
        if (DYNAMIC_TOOL_PATTERNS.some(p => p.test(line))) {
          findings.push(createFinding({
            rule: 'HERMES_FUNCTION_CALL_NO_ALLOWLIST', severity: 'critical',
            title: 'Tool dispatched from LLM output without allowlist check',
            description: 'Tool name sourced directly from LLM — prompt injection could hijack execution.',
            file, line: i + 1, matched: line.trim().slice(0, 120), category: 'llm',
            remediation: \`Check against ALLOWED_TOOLS before dispatch:\\n  if (!ALLOWED_TOOLS.includes(toolName)) throw new Error('Unknown tool: ' + toolName);\`,
            confidence: 'high',
          }));
        }
      }
    }
${memoryChecks}
    return findings;
  }
}
`;
}

export function generateGitHubWorkflow(config: HermesConfig): string {
  return `name: Ship Safe — Hermes Security Audit

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master]

jobs:
  hermes-audit:
    name: Hermes Security Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Run Ship Safe — Hermes Audit
        id: audit
        run: |
          npx ship-safe audit . --hermes-only --fail-below baseline --json > audit-result.json || true
          echo "score=$(cat audit-result.json | jq -r '.score // 0')" >> \$GITHUB_OUTPUT
          echo "findings=$(cat audit-result.json | jq -r '.findings | length // 0')" >> \$GITHUB_OUTPUT

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const score = '$\{{ steps.audit.outputs.score }}';
            const findings = '$\{{ steps.audit.outputs.findings }}';
            const grade = score >= 90 ? 'A' : score >= 80 ? 'B' : score >= 70 ? 'C' : score >= 60 ? 'D' : 'F';
            const emoji = score >= 80 ? '✅' : score >= 60 ? '⚠️' : '❌';
            await github.rest.issues.createComment({
              ...context.repo, issue_number: context.issue.number,
              body: [
                '## ' + emoji + ' Ship Safe — Hermes Security Report',
                '| Score | Grade | Findings |',
                '|-------|-------|----------|',
                \`| \${score}/100 | \${grade} | \${findings} |\`,
                '',
                score < 70 ? '> ⚠️ Run \`npx ship-safe audit . --agentic 3\` locally to auto-fix findings.' : '> Security posture looks good.',
                '_[Ship Safe](https://shipsafecli.com) · [Hermes Security](https://shipsafecli.com/blog/hermes-agent-security-tool-registry-poisoning-function-call-injection)_',
              ].join('\\n'),
            });

      - name: Enforce baseline
        run: npx ship-safe audit . --hermes-only --fail-below baseline
`;
}

export function generateGitLabCI(_config: HermesConfig): string {
  return `hermes-security-audit:
  stage: test
  image: node:20-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npx ship-safe audit . --hermes-only --fail-below baseline
`;
}

export function generateBaseline(config: HermesConfig): string {
  return JSON.stringify(
    {
      score: 0,
      date: new Date().toISOString().split('T')[0],
      findings: 0,
      note: 'Run `npx ship-safe audit .` to populate. CI compares against this.',
      tools: config.tools.map(t => t.name),
      memoryLayers: config.memoryLayers,
      hasSubAgents: config.hasSubAgents,
    },
    null,
    2,
  );
}

export function generateSetupGuide(config: HermesConfig): string {
  const toolList = config.tools
    .map(t => `- \`${t.name}\`${t.sourceUrl ? ` — ${t.sourceUrl}` : ' (local)'}`)
    .join('\n');

  return `# Ship Safe × Hermes — Security Setup

Generated ${new Date().toISOString().split('T')[0]} for **${config.projectName || 'my-hermes-agent'}**.

## Registered tools

${toolList}

## Next steps

1. Run your first audit: \`npx ship-safe audit .\`
2. Fix findings: \`npx ship-safe audit . --agentic 3 --agentic-target 80\`
3. Commit and push — CI runs on every PR

---
_[Ship Safe](https://shipsafecli.com) v8.0.0_
`;
}

// ── Build all files ────────────────────────────────────────────────────────

export function generateAllFiles(config: HermesConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [
    {
      path: config.manifestPath || 'agent-manifest.json',
      content: generateAgentManifest(config),
    },
    {
      path: '.ship-safe/agents/hermes-policy.js',
      content: generateHermesPolicy(config),
    },
    {
      path: '.ship-safe/hermes-baseline.json',
      content: generateBaseline(config),
    },
    {
      path: 'SHIP_SAFE_SETUP.md',
      content: generateSetupGuide(config),
    },
  ];

  if (config.ciProvider === 'github') {
    files.push({
      path: '.github/workflows/ship-safe-hermes.yml',
      content: generateGitHubWorkflow(config),
    });
  } else if (config.ciProvider === 'gitlab') {
    files.push({
      path: 'ship-safe-hermes-ci.yml',
      content: generateGitLabCI(config),
    });
  }

  return files;
}

// ── Token encode/decode (base64url, no DB needed) ──────────────────────────

export function encodeConfig(config: HermesConfig): string {
  return Buffer.from(JSON.stringify(config)).toString('base64url');
}

export function decodeConfig(token: string): HermesConfig | null {
  try {
    return JSON.parse(Buffer.from(token, 'base64url').toString('utf-8')) as HermesConfig;
  } catch {
    return null;
  }
}
